// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/keshvan/todo-docker-lab/internal/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, todo1 *todo.Todo) error {
	ret := _mock.Called(ctx, todo1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *todo.Todo) error); ok {
		r0 = returnFunc(ctx, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - todo1 *todo.Todo
func (_e *MockRepository_Expecter) Create(ctx interface{}, todo1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, todo1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, todo1 *todo.Todo)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *todo.Todo
		if args[1] != nil {
			arg1 = args[1].(*todo.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, todo1 *todo.Todo) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll(ctx context.Context, priority *todo.Priority) ([]todo.Todo, error) {
	ret := _mock.Called(ctx, priority)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *todo.Priority) ([]todo.Todo, error)); ok {
		return returnFunc(ctx, priority)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *todo.Priority) []todo.Todo); ok {
		r0 = returnFunc(ctx, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *todo.Priority) error); ok {
		r1 = returnFunc(ctx, priority)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - priority *todo.Priority
func (_e *MockRepository_Expecter) GetAll(ctx interface{}, priority interface{}) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, priority)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(ctx context.Context, priority *todo.Priority)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *todo.Priority
		if args[1] != nil {
			arg1 = args[1].(*todo.Priority)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(todos []todo.Todo, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, priority *todo.Priority) ([]todo.Todo, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockRepository
func (_mock *MockRepository) GetById(ctx context.Context, id int64) (*todo.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*todo.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *todo.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockRepository_GetById_Call {
	return &MockRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockRepository_GetById_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetById_Call) Return(todo1 *todo.Todo, err error) *MockRepository_GetById_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, id int64) (*todo.Todo, error)) *MockRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, id int64, todo1 *todo.Todo) error {
	ret := _mock.Called(ctx, id, todo1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *todo.Todo) error); ok {
		r0 = returnFunc(ctx, id, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - todo1 *todo.Todo
func (_e *MockRepository_Expecter) Update(ctx interface{}, id interface{}, todo1 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, todo1)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, id int64, todo1 *todo.Todo)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *todo.Todo
		if args[2] != nil {
			arg2 = args[2].(*todo.Todo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, todo1 *todo.Todo) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
