// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHandler
func (_mock *MockHandler) Create(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) Create(w interface{}, r interface{}) *MockHandler_Create_Call {
	return &MockHandler_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *MockHandler_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Create_Call) Return() *MockHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_Create_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_Create_Call {
	_c.Run(run)
	return _c
}

// GetAll provides a mock function for the type MockHandler
func (_mock *MockHandler) GetAll(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) GetAll(w interface{}, r interface{}) *MockHandler_GetAll_Call {
	return &MockHandler_GetAll_Call{Call: _e.mock.On("GetAll", w, r)}
}

func (_c *MockHandler_GetAll_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_GetAll_Call) Return() *MockHandler_GetAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_GetAll_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_GetAll_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type MockHandler
func (_mock *MockHandler) GetByID(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) GetByID(w interface{}, r interface{}) *MockHandler_GetByID_Call {
	return &MockHandler_GetByID_Call{Call: _e.mock.On("GetByID", w, r)}
}

func (_c *MockHandler_GetByID_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_GetByID_Call) Return() *MockHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_GetByID_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type MockHandler
func (_mock *MockHandler) Update(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) Update(w interface{}, r interface{}) *MockHandler_Update_Call {
	return &MockHandler_Update_Call{Call: _e.mock.On("Update", w, r)}
}

func (_c *MockHandler_Update_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Update_Call) Return() *MockHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_Update_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_Update_Call {
	_c.Run(run)
	return _c
}
